# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: sasToken
    type: string
    default:'?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-02-13T23:14:45Z&st=2024-02-13T15:14:45Z&spr=https&sig=0%2BA1EzuF%2BxUPAfcZlygtELYehadNfpicmtAc3gdGs88%3D'

pool: default 

steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'c:\temps2\'
    Destination: 'AzureBlob'
    storage: 'copyteststo'
    containerName: 'copytest'
    additionalArgumentsForBlobCopy: '--recursive=true'
    sasToken: '${{ parameters.sasToken }}'
