# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default
steps:

- task: AzureFileCopy@5
  inputs:
    SourcePath: '\\51.143.221.4\copytest\'
    azureSubscription: 'Azure subscription 1(9b650b16-d3a2-4e6c-ba40-e19815b48888)'
    Destination: 'AzureBlob'
    storage: 'copyteststo'
    ContainerName: 'copytest'
    BlobPrefix: 'copy/'