variables:
  buildConfiguration: 'Release'

stages:
- stage: Deploy
  pool: 
   name: local
   demands:
    - agent.name -equals local
 
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'dotnet-calc'
    appType: 'webAppLinux'
    appName: 'dotnetcalc-webapp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'