# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: 'c:\copysource'
    MachineNames: '51.143.221.4'
    AdminUserName: 'newadmin'
    AdminPassword: 'My 1 dog is Buddy'
    TargetPath: 'C:\copydest'
    CleanTargetBeforeCopy: true
